name: Auto PR to main

on:
  push:
    branches:
      - "bot/count-files"

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        destination_branch: "main"
        source_branch: "bot/count-files"
        pr_title: "Automated PR to Main"
        pr_body: "Please review updates from bot/count-files."
    # steps:
    # - uses: actions/checkout@v2
    # - name: Create Pull Request
    #   uses: repo-sync/pull-request@v2
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     destination_branch: "main"
    #     source_branch: "bot/count-files"
    #     pr_title: "Automated PR to Main"
    #     pr_body: "Update main branch with changes from develop."
